### ISSUE TITLE
panic: (*logrus.Entry)

### ISSUE THREAD

**Issue by mbrevda** [wercker/wercker#112]
Version: `wercker version 1.0.407 (Compiled at: 2016-02-12T23:57:08Z, Git commit: ff5c0069ed0f600c775f91836865728ac559cad4)`

Running `dev --docker-local --publish 8090:80 --attach-on-error`. Instead of attaching on error, I get the following:

```
WARNING Box container has already stopped.
panic: (*logrus.Entry) (0x6c0920,0xc820199900)

goroutine 1 [running]:
github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus.(*Entry).log(0xc820199900, 0x0, 0xc820216ba0, 0x12)
	/gopath/src/github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus/entry.go:103 +0x5fb
github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc820199900, 0xc82042e8a0, 0x1, 0x1)
	/gopath/src/github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus/entry.go:148 +0x7c
github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus.(*Entry).Panicln(0xc820199900, 0xc82042e968, 0x1, 0x1)
	/gopath/src/github.com/wercker/wercker/vendor/github.com/Sirupsen/logrus/entry.go:241 +0x120
github.com/wercker/wercker/docker.(*DockerBox).RecoverInteractive(0xc8200b61e0, 0xc82014c580, 0x10, 0xcf1b60, 0xc820034580, 0xcf1a58, 0xc82033d700, 0x0, 0x0)
	/gopath/src/github.com/wercker/wercker/docker/box.go:302 +0x16c
github.com/wercker/wercker/cmd.(*Runner).RunStep(0xc820152c30, 0xc820193c70, 0xcf1a58, 0xc82033d700, 0x6, 0x0, 0x0, 0x0)
	/gopath/src/github.com/wercker/wercker/cmd/runner.go:657 +0x8c3
github.com/wercker/wercker/cmd.executePipeline(0xcec300, 0xc8200bbb90, 0xc82001a780, 0xc820152be0, 0xc820156ea0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/wercker/wercker/cmd/main.go:971 +0x1cf9
github.com/wercker/wercker/cmd.cmdDev(0xcec300, 0xc8200bbb90, 0xc82001a780, 0xc820152be0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/wercker/wercker/cmd/main.go:404 +0x37b
github.com/wercker/wercker/cmd.glob.func2(0xc8200ac540)
	/gopath/src/github.com/wercker/wercker/cmd/main.go:96 +0x7f8
github.com/wercker/wercker/vendor/github.com/codegangsta/cli.Command.Run(0x6db1f8, 0x3, 0x0, 0x0, 0x75d680, 0x1f, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/wercker/wercker/vendor/github.com/codegangsta/cli/command.go:113 +0x10ab
github.com/wercker/wercker/vendor/github.com/codegangsta/cli.(*App).Run(0xc820063ba0, 0xc82000a120, 0x6, 0x6, 0x0, 0x0)
	/gopath/src/github.com/wercker/wercker/vendor/github.com/codegangsta/cli/app.go:156 +0xbda
main.main()
	/gopath/src/github.com/wercker/wercker/main.go:25 +0x49

goroutine 5 [syscall]:
os/signal.loop()
	/goroot/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/goroot/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x807e50, 0xc820032728, 0x6dd3f0, 0x6, 0x2cc18, 0x2)
	/goroot/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820032728, 0x0, 0x18)
	/goroot/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820032728)
	/goroot/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/goroot/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [chan receive]:
github.com/wercker/wercker/util.(*SignalMonkey).Register.func1(0xc820012f40)
	/gopath/src/github.com/wercker/wercker/util/signal.go:95 +0x76
created by github.com/wercker/wercker/util.(*SignalMonkey).Register
	/gopath/src/github.com/wercker/wercker/util/signal.go:106 +0x111

goroutine 8 [chan receive]:
github.com/wercker/wercker/util.(*SignalMonkey).Register.func1(0xc820012f80)
	/gopath/src/github.com/wercker/wercker/util/signal.go:95 +0x76
created by github.com/wercker/wercker/util.(*SignalMonkey).Register
	/gopath/src/github.com/wercker/wercker/util/signal.go:106 +0x111

goroutine 225 [semacquire]:
sync.runtime_Syncsemacquire(0xc820304100)
	/goroot/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8203040f0)
	/goroot/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc8203040c0, 0xc820522038, 0x200, 0x200, 0x0, 0x0, 0x0)
	/goroot/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc820034040, 0xc820522038, 0x200, 0x200, 0xc82002550c, 0x0, 0x0)
	/goroot/src/io/pipe.go:134 +0x50
io.ReadAtLeast(0xd2faa8, 0xc820034040, 0xc820522038, 0x200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/goroot/src/io/io.go:298 +0xe6
io.ReadFull(0xd2faa8, 0xc820034040, 0xc820522038, 0x200, 0x200, 0x27a18d, 0x0, 0x0)
	/goroot/src/io/io.go:316 +0x62
archive/tar.(*Reader).readHeader(0xc820522000, 0xd2faa8)
	/goroot/src/archive/tar/reader.go:441 +0x10c
archive/tar.(*Reader).Next(0xc820522000, 0xd2fa98, 0x0, 0x0)
	/goroot/src/archive/tar/reader.go:98 +0xa0
github.com/wercker/wercker/util.UntarOne(0x6ef190, 0xb, 0xcec220, 0xc8202c89a0, 0xd2fa78, 0xc820034040, 0x0, 0x0)
	/gopath/src/github.com/wercker/wercker/util/util.go:84 +0x11f
github.com/wercker/wercker/docker.(*DockerStep).CollectFile.func1(0xc82000bc20, 0x6ef190, 0xb, 0xcec220, 0xc8202c89a0, 0xc820034040)
	/gopath/src/github.com/wercker/wercker/docker/step.go:99 +0xaf
created by github.com/wercker/wercker/docker.(*DockerStep).CollectFile
	/gopath/src/github.com/wercker/wercker/docker/step.go:100 +0x3e6

goroutine 127 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc82028b080, 0xc820219a40, 0xc82028af60, 0xc82028b020)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 301 [IO wait]:
net.runtime_pollWait(0xced408, 0x72, 0xc820010190)
	/goroot/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202b0220, 0x72, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202b0220, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202b01c0, 0xc820397000, 0x400, 0x400, 0x0, 0xce7050, 0xc820010190)
	/goroot/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8204ec068, 0xc820397000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/goroot/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82026ac30, 0xd27050, 0xc8204ec068, 0x5, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc820510b00, 0x807e17, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc820510b00, 0xc8202a2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0xd2b5b8, 0xc820510b00, 0xc8203b7a78, 0xc8202a2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82033d440, 0xc8202a2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8202c0960)
	/goroot/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8202c0960, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8203b7a20)
	/goroot/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:685 +0xc78

goroutine 43 [IO wait]:
net.runtime_pollWait(0xced108, 0x72, 0xc820010190)
	/goroot/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820060220, 0x72, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820060220, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200601c0, 0xc8201c0400, 0x400, 0x400, 0x0, 0xce7050, 0xc820010190)
	/goroot/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201a2000, 0xc8201c0400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/goroot/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820350090, 0xd27050, 0xc8201a2000, 0x5, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200962c0, 0x807e17, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8200962c0, 0xc8200e8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0xd2b5b8, 0xc8200962c0, 0xc8200b4108, 0xc8200e8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82033c000, 0xc8200e8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8202fc720)
	/goroot/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8202fc720, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200b40b0)
	/goroot/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:685 +0xc78

goroutine 96 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc82028ce40, 0xc820219a40, 0xc82028cd20, 0xc82028cde0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 69 [IO wait]:
net.runtime_pollWait(0xced288, 0x72, 0xc820010190)
	/goroot/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820173b80, 0x72, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820173b80, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820173b20, 0xc8200b9000, 0x400, 0x400, 0x0, 0xce7050, 0xc820010190)
	/goroot/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82052a028, 0xc8200b9000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/goroot/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820307470, 0xd27050, 0xc82052a028, 0x5, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8201a6840, 0x807e17, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8201a6840, 0xc8201e0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0xd2b5b8, 0xc8201a6840, 0xc8202612e8, 0xc8201e0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8205a0600, 0xc8201e0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820597c20)
	/goroot/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820597c20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820261290)
	/goroot/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:685 +0xc78

goroutine 66 [IO wait]:
net.runtime_pollWait(0xced1c8, 0x72, 0xc820010190)
	/goroot/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202fa1b0, 0x72, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202fa1b0, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202fa150, 0xc82001c800, 0x800, 0x800, 0x0, 0xce7050, 0xc820010190)
	/goroot/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82052a018, 0xc82001c800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/goroot/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8204e1f50, 0xd27050, 0xc82052a018, 0x5, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8201a62c0, 0x807e17, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8201a62c0, 0xc820023000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0xd2b5b8, 0xc8201a62c0, 0xc8200b4898, 0xc820023000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82029c320, 0xc820023000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8202dd5c0)
	/goroot/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8202dd5c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200b4840)
	/goroot/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:685 +0xc78

goroutine 67 [select]:
net/http.(*persistConn).writeLoop(0xc8200b4840)
	/goroot/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:686 +0xc9d

goroutine 44 [select]:
net/http.(*persistConn).writeLoop(0xc8200b40b0)
	/goroot/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:686 +0xc9d

goroutine 70 [select]:
net/http.(*persistConn).writeLoop(0xc820261290)
	/goroot/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:686 +0xc9d

goroutine 134 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc82028d5c0, 0xc820219a40, 0xc82028d4a0, 0xc82028d560)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 282 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8201f9f80, 0xc820219a40, 0xc8201f9e60, 0xc8201f9f20)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 76 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8202c1c20, 0xc820219a40, 0xc8202c1b00, 0xc8202c1bc0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 80 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc82028c300, 0xc820219a40, 0xc82028c1e0, 0xc82028c2a0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 28 [chan receive]:
github.com/wercker/wercker/core.(*Sender).Read(0xc8204ec000, 0xc82009e000, 0x8000, 0x8000, 0x2d, 0x0, 0x0)
	/gopath/src/github.com/wercker/wercker/core/session.go:58 +0x67
io.copyBuffer(0xcf2a28, 0xc820271420, 0xcf2540, 0xc8204ec000, 0xc82009e000, 0x8000, 0x8000, 0x1d1b, 0x0, 0x0)
	/goroot/src/io/io.go:381 +0x247
io.Copy(0xcf2a28, 0xc820271420, 0xcf2540, 0xc8204ec000, 0xc820271420, 0x0, 0x0)
	/goroot/src/io/io.go:351 +0x64
github.com/wercker/wercker/vendor/github.com/fsouza/go-dockerclient.(*Client).hijack.func1.2(0xc8200162d0, 0xcf2970, 0xc820271420, 0xc8203de0c0)
	/gopath/src/github.com/wercker/wercker/vendor/github.com/fsouza/go-dockerclient/client.go:664 +0x92
created by github.com/wercker/wercker/vendor/github.com/fsouza/go-dockerclient.(*Client).hijack.func1
	/gopath/src/github.com/wercker/wercker/vendor/github.com/fsouza/go-dockerclient/client.go:670 +0x3a2

goroutine 91 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc82028c9c0, 0xc820219a40, 0xc82028c8a0, 0xc82028c960)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 123 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc82028ac00, 0xc820219a40, 0xc82028aae0, 0xc82028aba0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 106 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8202fd3e0, 0xc820219a40, 0xc8202fd2c0, 0xc8202fd380)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 302 [select]:
net/http.(*persistConn).writeLoop(0xc8203b7a20)
	/goroot/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/goroot/src/net/http/transport.go:686 +0xc9d

goroutine 184 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc820596060, 0xc820219a40, 0xc8202fdf20, 0xc820596000)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 32 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8203de540, 0xc820219a40, 0xc8203de420, 0xc8203de4e0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 180 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8202fdc20, 0xc820219a40, 0xc8202fdb00, 0xc8202fdbc0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 154 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc82028b800, 0xc820219a40, 0xc82028b6e0, 0xc82028b7a0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 173 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8203df200, 0xc820219a40, 0xc8203df0e0, 0xc8203df1a0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 168 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8203deba0, 0xc820219a40, 0xc8203dea80, 0xc8203deb40)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 193 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8203df620, 0xc820219a40, 0xc8203df500, 0xc8203df5c0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 257 [semacquire]:
sync.runtime_Syncsemacquire(0xc820406280)
	/goroot/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc820406270)
	/goroot/src/sync/cond.go:62 +0x9b
io.(*pipe).read(0xc820406240, 0xc8200c1238, 0x200, 0x200, 0x0, 0x0, 0x0)
	/goroot/src/io/pipe.go:52 +0x2d2
io.(*PipeReader).Read(0xc82052a078, 0xc8200c1238, 0x200, 0x200, 0xc82002800c, 0x0, 0x0)
	/goroot/src/io/pipe.go:134 +0x50
io.ReadAtLeast(0xd2faa8, 0xc82052a078, 0xc8200c1238, 0x200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/goroot/src/io/io.go:298 +0xe6
io.ReadFull(0xd2faa8, 0xc82052a078, 0xc8200c1238, 0x200, 0x200, 0x27a18d, 0x0, 0x0)
	/goroot/src/io/io.go:316 +0x62
archive/tar.(*Reader).readHeader(0xc8200c1200, 0xd2faa8)
	/goroot/src/archive/tar/reader.go:441 +0x10c
archive/tar.(*Reader).Next(0xc8200c1200, 0xd2fa98, 0x0, 0x0)
	/goroot/src/archive/tar/reader.go:98 +0xa0
github.com/wercker/wercker/util.UntarOne(0x6ef190, 0xb, 0xcec220, 0xc8200e2cb0, 0xd2fa78, 0xc82052a078, 0x0, 0x0)
	/gopath/src/github.com/wercker/wercker/util/util.go:84 +0x11f
github.com/wercker/wercker/docker.(*DockerStep).CollectFile.func1(0xc8204ab5c0, 0x6ef190, 0xb, 0xcec220, 0xc8200e2cb0, 0xc82052a078)
	/gopath/src/github.com/wercker/wercker/docker/step.go:99 +0xaf
created by github.com/wercker/wercker/docker.(*DockerStep).CollectFile
	/gopath/src/github.com/wercker/wercker/docker/step.go:100 +0x3e6

goroutine 198 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8203dfbc0, 0xc820219a40, 0xc8203dfaa0, 0xc8203dfb60)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 202 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8203dff80, 0xc820219a40, 0xc8203dfe60, 0xc8203dff20)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 206 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8201f83c0, 0xc820219a40, 0xc8201f82a0, 0xc8201f8360)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 242 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8201f87e0, 0xc820219a40, 0xc8201f86c0, 0xc8201f8780)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 247 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8201f8de0, 0xc820219a40, 0xc8201f8cc0, 0xc8201f8d80)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 253 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8201f9320, 0xc820219a40, 0xc8201f9200, 0xc8201f92c0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 256 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8201f9680, 0xc820219a40, 0xc8201f9560, 0xc8201f9620)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 276 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8201f9a40, 0xc820219a40, 0xc8201f9920, 0xc8201f99e0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 141 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc82028dc20, 0xc820219a40, 0xc82028db00, 0xc82028dbc0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 287 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc8203885a0, 0xc820219a40, 0xc820388480, 0xc820388540)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398

goroutine 296 [select]:
github.com/wercker/wercker/core.(*Session).SendChecked.func2(0xc82038a540, 0xc820219a40, 0xc82038a420, 0xc82038a4e0)
	/gopath/src/github.com/wercker/wercker/core/session.go:278 +0x180
created by github.com/wercker/wercker/core.(*Session).SendChecked
	/gopath/src/github.com/wercker/wercker/core/session.go:287 +0x398
```

**Comment by Tonnu** [comment]
If you're still running into this problem and for future reference: I think this is because of the incorrect `--publish` flag usage. It should be `--expose-ports` now as per https://github.com/wercker/wercker/pull/161
