### ISSUE TITLE
Panic when Docker repository invalid

### ISSUE THREAD

**Issue by jwolski2** [wercker/wercker#306]
The following happens if you reference a box in your pipeline that points to an invalid Docker repository or register:

```
--> No Docker host specified, checking: /var/run/docker.sock
--> Executing pipeline
--> Running step: setup environment
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x745b32]

goroutine 1 [running]:
panic(0x9d66e0, 0xc42000e0a0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/wercker/wercker/vendor/github.com/wercker/docker-check-access.DockerAuth.Repository(0x0, 0x0, 0xc42013f180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x545a20, ...)
    /go/src/github.com/wercker/wercker/vendor/github.com/wercker/docker-check-access/docker-auth.go:126 +0x42
github.com/wercker/wercker/vendor/github.com/wercker/docker-check-access.DockerAuthV1.Repository(0xc420323380, 0x0, 0x0, 0x0, 0x0)
    <autogenerated>:25 +0x78
github.com/wercker/wercker/docker.(*DockerBox).Fetch(0xc4200e84b0, 0x7f9c039f8708, 0xc4202c5a70, 0xc42031cae0, 0x0, 0x0, 0x0)
    /go/src/github.com/wercker/wercker/docker/box.go:527 +0x14f
github.com/wercker/wercker/cmd.(*Runner).SetupEnvironment(0xc420326370, 0x7f9c039f8708, 0xc4202c5a70, 0x0, 0x0, 0x0)
    /go/src/github.com/wercker/wercker/cmd/runner.go:530 +0x7af
github.com/wercker/wercker/cmd.executePipeline(0x7f9c039f8708, 0xc4202c5a70, 0xc4202d1800, 0xc420326000, 0xc420324840, 0x0, 0x0, 0x0)
    /go/src/github.com/wercker/wercker/cmd/main.go:937 +0x7e2
github.com/wercker/wercker/cmd.cmdBuild(0x7f9c039f7538, 0xc42006c398, 0xc4202d1800, 0xc420326000, 0xc42006c398, 0x0, 0xc420302b76)
    /go/src/github.com/wercker/wercker/cmd/main.go:413 +0xb0
github.com/wercker/wercker/cmd.glob..func1(0xc4200f29c0)
    /go/src/github.com/wercker/wercker/cmd/main.go:69 +0x367
github.com/wercker/wercker/vendor/github.com/codegangsta/cli.Command.Run(0xa8df5f, 0x5, 0xa8ce0a, 0x1, 0xa93d10, 0xf, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/wercker/wercker/vendor/github.com/codegangsta/cli/command.go:113 +0x7bb
github.com/wercker/wercker/vendor/github.com/codegangsta/cli.(*App).Run(0xc4202f6340, 0xc42007e060, 0x2, 0x2, 0x0, 0x0)
    /go/src/github.com/wercker/wercker/vendor/github.com/codegangsta/cli/app.go:156 +0x630
main.main()
    /go/src/github.com/wercker/wercker/main.go:25 +0x53
```

Minimal reproduction.. Run `wercker build` against this:

```
build:
    box:
        id: :master-base
        username: username
        password: password
        registry: registry
    steps:
        - script: 
            name: echo it
            code: echo "hello, world!"
```

**Comment by faiq** [comment]
closed by #308
